### ISSUE TITLE
Connect SSO after login  

### ISSUE THREAD

**Issue by erlend-sh** [commune-os/weird#52]
As a complement to #35 we need a way for users to add their preferred social login after they’ve already logged in, since we don’t allow an existing user to log in via a social provider if the email match:

![IMG_2365](https://github.com/commune-os/weird/assets/583842/d0d2be2b-518b-4c62-8b0a-f8212f983299)

We just need a ‘Add login provider’ button at the bottom of the `https://weird.one/auth/v1/account` page.

(We are quickly filling up this account page, so we’ll need multiple tabs for it soon.)

**Comment by kimlimjustin** [comment]
Umm... Are we going to allow multiple social provider accounts linked to one weird account? Or are we allowing only one social provider account linked to an account?

The current implementation of Rauthy allows only one provider though (https://github.com/sebadob/rauthy/blob/e7415111426f1e2d6595ac26dc64305c79cc7632/rauthy-models/src/entity/users.rs#L54-L76)

**Comment by erlend-sh** [comment]
> only one social provider account linked to an account?

we’re fine with just that for now.

**Comment by kimlimjustin** [comment]
Pushed a PR for this (#58)
