### ISSUE TITLE
Update CLC Bot to use CLC instead of CLA in verbiage

### ISSUE THREAD

**Issue by zicklag** [commune-os/weird#59]
https://github.com/commune-os/weird/pull/43#issuecomment-2157981385

**Comment by erlend-sh** [comment]
Please make this change asap so that we don’t have any more scary ‘CLA’ mentions around.

**Comment by zicklag** [comment]
I forked the bot and did a dumb replace all CLA with CLC and switched to using our fork. Hopefully that will work. I'll close the issue, and we can re-open if we notice something off.
