### ISSUE TITLE
 `Node v16` deprecation warning in CI

### ISSUE THREAD

**Issue by azzamsa** [commune-os/weird#76]
I have made a relevant PR addressing this in upstream repo https://github.com/contributor-assistant/github-action/pull/156
Hopefully this will get rid of the warnings.

It is caused by `contributor-assistant/github-action@v2.4.0` as mentioned here:

``` 
CLCAssistant
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: contributor-assistant/github-action@v2.4.0.
```

![image](https://github.com/commune-os/weird/assets/17734314/5f2f5250-c69d-49af-ac32-49e731f2d766)

I have made a relevant PR addressing this in upstream repo https://github.com/contributor-assistant/github-action/pull/156

Related:
- https://github.com/commune-os/weird/blob/50137f81344cf3fa429738aea3cf560ec9d7d4c5/.github/workflows/check-for-clc.yaml#L21
- https://github.com/contributor-assistant/github-action/issues/149
- https://github.com/contributor-assistant/github-action/pull/156

**Comment by zicklag** [comment]
I merged that into our fork of CLC assistant, thanks! :+1:
