### ISSUE TITLE
Standardize Commit Message Format

### ISSUE THREAD

**Issue by azzamsa** [commune-os/weird#83]
Hi everyone, 👋🏽 

Should we start using a convention to standardize our commit messages? I propose we adopt the popular Angular [Commit Message Format](https://github.com/angular/angular/blob/main/CONTRIBUTING.md#-commit-message-format).

It's fine not to include the `scope` for now, but we should at least use the defined prefixes. This will prevent contributors from using arbitrary prefixes. Here are the prefixes we should use for each commit:

- **build**: Changes that affect the build system or external dependencies (example scopes: gulp, broccoli, npm)
- **ci**: Changes to our CI configuration files and scripts (examples: CircleCi, SauceLabs)
- **docs**: Documentation only changes
- **feat**: A new feature
- **fix**: A bug fix
- **perf**: A code change that improves performance
- **refactor**: A code change that neither fixes a bug nor adds a feature
- **test**: Adding missing tests or correcting existing tests

What do you all think?
We should add this to our `CONTRIBUTING.md` documentation if we agree.

**Comment by zicklag** [comment]
Yes, I'm good with it. I've been using conventional commits, without scopes, for a bit now. 

I'm not sure we need them yet, but I've been using these CI jobs to catch unconventional commits in Bones:

- https://github.com/fishfolk/bones/blob/main/.github/workflows/merge-group-commit-lint.yml
- https://github.com/fishfolk/bones/blob/main/.github/workflows/pul-requests.yml

I haven't bothered with merge queues or anything yet, though. I've just been squash-merging pull requests ( where I can modify the commit message before merging ), and pushing directly to mater for many of my changes, just for speed's sake.

**Comment by azzamsa** [comment]
> I'm not sure we need them yet, but I've been using these CI jobs to catch unconventional commits in Bones:

>  I've just been squash-merging pull requests

I am okay with the current situation; I just worry the repo will contain undesired formats or prefixes. Fortunately, we are on the same page.

**Comment by azzamsa** [comment]
Closing this issue because it is currently non-actionable.
