### ISSUE TITLE
Hide the Work Compensation / Capacity Fields on Weird.One

### ISSUE THREAD

**Issue by zicklag** [commune-os/weird#89]
These fields are specifically for the Muni.Town use-case.

**Comment by erlend-sh** [comment]
These fields might form the foundation of what would be a user’s ’NoSP Profile’, I.e. another sub-page alongside masto, github et.al.

**Comment by zicklag** [comment]
Got it. I think I'm starting to get a little bit more of an idea of how things like links, pages, projects, lists, etc. are going to generalize, aka. what is the same between them and how we can build them on the same simple data foundations.

Still a little fuzzy in my head, but I think a little more thought and experimentation will make it more clear.

**Comment by erlend-sh** [comment]
> Still a little fuzzy in my head

Same! 😂  but I'll know it when I see it.
