### ISSUE TITLE
Keep session alive

### ISSUE THREAD

**Issue by erlend-sh** [commune-os/weird#97]
Right now we seem to be logging users out after just a few hours of inactivity.

We need this raised to weeks. Not sure what the industry standard is here, though that not necessarily the Best Practice anyhow.

**Comment by zicklag** [comment]
Yeah, I noticed that. Should be a simple config change. GitHub keeps me logged in for weeks, so, we should be fine. :D

**Comment by zicklag** [comment]
Fixed this earlier. :wrench:
